### PR TITLE
Optimized for some nvidian cards

### PR DESCRIPTION
**Pull request by davilizh**
The code is optimized for GTX1060, can improve GTX1060 with 2 GPC performance by 15%, and GTX1060 with 1 GPC performance by more than 30%. Meanwhile, it also increases performance on GTX1070 by 3%, on Telsla M60 by 2%, and should also benefit other chips.

1. **ethash_cuda_miner_kernel.cu**

We have commented out "launch_bounds" in the code. launch_bound is discussed in http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#axzz4fzSzZc9p in detail.

2. **dagger_shuffle.cuh**

1) We moved around and reduced variable definitions to the minimum required. The compiler should have been able to do this analysis, but it never hurts to help out the compiler.
The state in compute_hash of dagger_shuffle.cuh is modified.
2) We simplify the nested if/else blocks into a switch statement.
3) We simplify control flow. Remove the conditional from the inner loop so all threads calculate the value, and then all threads use a __shfl to read thread t's value (throwing away the rest of the threads' calculated value).
4) We increase the total number of LDGs to increase occupancy. We define PARALLEL_HASH to let each warp have PARALLEL_HASH LDGs in-flight at a time, not 1 at a time, which is the original case.
Every thread is the master for calculating one hash value. Each thread initializes its version of state using keccak_f1600_init. Then in the main loop: When i=0 threads 0-7 copy the values of thread 0's state[0-7] into each threads' shuffle[0-7], do the main computation, and then thread 0 captures the result of shuffle[0-3] into state[8-11]. On the next loop when i=1 threads 0-7 copy the values of thread 1's state[0-7] into each threads' shuffle[0-7], do the main computation, and then thread 1 captures the result of shuffle[0-3] into state[8-11].
With the modification this is changed so that if PARALLEL_HASH=2: When i=0 threads 0-7 copy the values of thread 0's state[0-7] into each threads' shuffle[0][0-7] and thread 1's state[0-7] into each threads' shuffle[1][0-7]. They do the main computation on these 2 shuffle vectors in parallel. Then thread 0 captures the result of shuffle[0][0-3] into its state[8-11] and thread 1 captures the result of shuffle[1][0-3] into its state[8-11].

3. **keccak.cuh** 

Since the input argument uint2 *s is changed in dagger_shuffle.cuh, we have to modify keccak_f1600_init and keccak_f1600_final in keccak.cuh accordingly.

### CODE REVIEW

**Comment by davilizh** [comment]
The first commit is wrong since I added the 3 files to the root directory: "cpp-ethereum", while the correct path should be "cpp-ethereum/libethash-cuda". The second commit fix this issue.

**Comment by zachgrayio** [comment]
@davilizh I'm curious what the CUDA hashrate looks like for the GRID K520 with current builds, got any benchmarks to share?

**Comment by davilizh** [comment]
I do not have K520 at hand, it is tested by someone else in other community. 
The result is as follows. 
However, I don't think the result is 100% reasonable as the min value is 0. I will ask him to test again if I can get contact with him.

"min/mean/max: 0/4858402/7689557 H/s
inner mean: 5534151 H/s"

**Comment by FUNtasticOne** [comment]
Would love to test this build with my GTX1060 graphics cards. I´m not a developer or programmer, and I´m completely new to GitHub, so I hope my commentary here is not too annoying.
I tried to build this repository as descriped in the instructions. There is a "getstuff.bat", which should download some needed files. Unfortunately this isn´t working. I looked into the batch file and i can´t even download the files manually, because the site is not reachable.
So I would like to ask cautiously whether the possibility exists to download the compiled release from somewhere?
Again, if my question is out of place, I beg your pardon.
Regards

**Comment by Cyclenerd** [comment]
Hi,

compiled it successfully under Ubuntu 16.04.2 with CUDA 8 and NVIDIA drivers 381.22:

```
apt-get install -y cuda-command-line-tools-8-0
git clone "https://github.com/davilizh/cpp-ethereum.git"
cd cpp-ethereum
git checkout optimized_for_some_nvidian_cards
mkdir build
cd build
cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DBUNDLE=cudaminer ..
make -j8
```
I have 2 GTX 1060 graphics cards:

```
name, power.draw [W], fan.speed [%], temperature.gpu, clocks.current.video [MHz], clocks.current.memory [MHz]
GeForce GTX 1060 6GB, 70.14 W, 70 %, 61, 1328 MHz, 4201 MHz
GeForce GTX 1060 6GB, 70.79 W, 70 %, 53, 1417 MHz, 4201 MHz
```
Previously, each line was 41.94 MH/s. With your patch comes more often 47.19MH/s. So works for me. Do I need to adjust something on the graphics or memory clock to make 47 stable?

MANY THANKS!

**Comment by Genoil** [comment]
Wow nice one! I don't have any Nvidia cards anymore to test, but it is tempting to merge! I suggest you submit this to @chfast his fork too, if you haven't already.

**Comment by davilizh** [comment]
@Cyclenerd Thank you very much. Good news to know.

@FUNtasticOne which operation system are you using? If windows, you can download the exe from here: https://ci.appveyor.com/project/ethereum-mining/ethminer/build/93/job/ss7k95dsy1kly4vl/artifacts. If linux, then do as Cyclenerd's flow.

@Genoil Would be great if my code can be merged to the master branch. 
Thank you for your advice. Actually, I have created a pull request to chfast's fork: https://github.com/ethereum-mining/ethminer/pull/18#issuecomment-310846114.

**Comment by FUNtasticOne** [comment]
Thank you @davilizh I´m on windows and just downloaded the exe.

For me there is no improvemnt of the hashrate..
I just tested with one Palit GTX1060 6GB RAM.
First tested with NVIDIA driver version 376.53 on Windows 10 x64.
Even after upgrading the driver to the latest version (382.53) there is no improvement.
The Hash rate is almost exactly 20 MH/s with the slightly overclocked card, both before and after changing the exe file.
Of course I´m using CUDA interface for mining.

Please let me know if you´re interested in additional information.

Thank you again!

**Comment by davilizh** [comment]
@FUNtasticOne Can you check the runtime working frequency of your DRAM? Mine works at **4.5GHz**. and I guess that yours should be **4.0 GHz** ( from https://www.lelong.com.my/9734-palit-gtx1060-jetstream-6gb-ddr5-192bit-gtx1060-cwchoo85-188799203-2017-04-Sale-P.htm).

**Comment by FUNtasticOne** [comment]
@davilizh My DRAM Frequenzy is 4.0 Ghz stock, overclocked to 4.1 GHz. GPU-Z says 2052 MHz which has to be doubled, so you´re right.

**Comment by UNST4BL3** [comment]
Seeing significantly more performance with this patch, thanks @davilizh.

**Comment by TitanicFreak** [comment]
Went from 22Mh/s per card to about 29Mh/s per card with this patch. Amazing work @davilizh!

**Comment by seedlord** [comment]
Will this update come into the release-section? 
I cant compile by myself and would like to try it out on a GB GTX1070 Gaming G1
Currently i am at 30.9MH/s with 88% Powerload and 8808Mhz Memory Clock.

**Comment by chfast** [comment]
@seedlord, for Windows you can test this build: https://ci.appveyor.com/project/ethereum-mining/ethminer/build/93/job/ss7k95dsy1kly4vl/artifacts.

**Comment by seedlord** [comment]
Thanks for link.
No difference for me. Still 30.9MH/s

**Comment by FUNtasticOne** [comment]
As already written above, for me there isn´t also any difference with the downloadable exe.
davilizh wrote that the first commit was wrong. Could it be the case that the downoadable build is the faulty one? 
Maybe someone who compiled by themself and had more performance after this can check it out for windows with the downloadable file?

**Comment by seedlord** [comment]
Windows exe is from date 9th July. The optimized code came out 6 days ago, so it should be 20th July or not?

**Comment by chfast** [comment]
The build comes from a PR to ethminer: https://github.com/ethereum-mining/ethminer/pull/18, but I'm guessing this one here implements the same optimization.

**Comment by ghost** [comment]
Okay, I've made some testing -- 6x1060 3GB:
Claymore 9.5 -> 136MH/s on screen + constant devfee DAG swap
Your optimized version -> 150MH/s
I used downloaded Win version from posts above to test... as .bat file included doesn't work, connection timeout to download page.
Good job mate!

**Comment by ggilyeat** [comment]
@deadgray What are your OC settings on your 3Gs? 

I've gone from ~19.5 (~117) with claymore to just under 23 (137) with the enhancements. 

Very, very impressed, sirs.

**Comment by ghost** [comment]
@ggilyeat +100 core + 860 mem, cards are with Samsung mem.
Ah, and 67% power set; whole rig uses just 540W from the wall. Amd miners can dream of that power eff. :-D

**Comment by juliotec** [comment]
How can i show the average hashrate to show how can i increase with this patch? Im testing with my Asus 1060 Dual OC 3GB

**Comment by juliotec** [comment]
I tested my Asus GTX 1060 Dual OC 3GB

Specs:

GPU Power : only 80%

GPU Clock: 2000 mhz (OC Stable)

Memory Clock: 9300 mhz (OC Stable)

# Ethminer

## before

ethminer -U -M

Trial 1... 22953902
Trial 2... 22976764
Trial 3... 23022626
Trial 4... 23045626
Trial 5... 22999672

min/mean/max: 22953902/22999718/23045626 H/s
inner mean: 22999687 H/s

## after

ethminer -U -M

Trial 1... 24377389
Trial 2... 24385488
Trial 3... 25032318
Trial 4... 24361208
Trial 5... 24417937

min/mean/max: 24361208/24514868/25032318 H/s

inner mean: 24393604 H/s

**Increase 6%**

# Claymore's v9.4

Same specs

22 mh/s

So ...

Ethmine: 24.393604 Mh/S

Claymore: 22 Mh/S without dev fee (using proxy named nofee 5.0)

**Increase 10.88%**

**Ethminer wins**

**Comment by marvykkio** [comment]
What version of genoil should I use? I just changed the .exe file from the version
1.1.7 does not work
help pls
4x 1070 gigabyte G1
windows 10 64 bit

**Comment by juliotec** [comment]
use this one https://ci.appveyor.com/api/buildjobs/ss7k95dsy1kly4vl/artifacts/build%2Fethminer-0.11.0.dev0-Windows.zip

the changes are not been merged in the master i think

**Comment by marvykkio** [comment]
This has been downloaded, I miss the version of ethermine.
What should I take 1.1.6? 1.1.7? 0.9.41 genoil.
Which I have to use

**Comment by marvykkio** [comment]
errore

VCruntime is also missing

**Comment by ghost** [comment]
@marvykkio you can find those files in your system, or in Visual Studio

**Comment by ovuncyazgan** [comment]
@davilizh I really want to test it out but cant get it working.I cant compile my own miner.  Downloaded exe and provide missing dll's but it gives me an error. If you can please share a complete folder. Thanks in advance. On Win10 x64 with 7 Asus GTX 1060 Dual 6 gb

**Comment by FUNtasticOne** [comment]
@ovuncyazgan 
I´ve just uploaded my complete folder to a filehoster. 
Note:
1. I just tried to download it for my own to test. Google Chrome seems to be blocking the download because it thinks there could be a virus in there. It is not! I know, you just have to believe me.
2. You have to change the starting batch file. There is my path for the exe deposited and my own etherum wallet.

I hope this helps!

http://www.xup.in/dl,15904893/mein.rar/

EDIT:
Those filehosters are horrible. Here is a different link to download:
http://s000.tinyupload.com/index.php?file_id=48522156841577617893

Please be sure to klick on the green link "mein.rar".

**Comment by ovuncyazgan** [comment]
@FUNtasticOne  thanks a lot. Going to try it now

**Comment by Kainzo** [comment]
Without overclocks, I still get worse performance on this optimized branch, with overclocks (and undervolts) I get 10-15% more.

**Comment by ghost** [comment]
Why has this been marked as "wontfix" ?

**Comment by ggilyeat** [comment]
Probably because Genoil updated the readme, earlier today, to say that he is retiring the project in favor of chfast's fork.

**Comment by ghost** [comment]
Which CUDA dll should I use? I have Win10/ GTX 1060 6gb

**Comment by TheMuff1nMan** [comment]
@FUNtasticOne, when i run the .bat file it opens the cmd window runs through some script and then closes. I'm not sure how to approach this.

**Comment by ovuncyazgan** [comment]
@TheMuff1nMan in bat file delete the file path before the ethminer.exe (E:\...) and try again

**Comment by FUNtasticOne** [comment]
@TheMuff1nMan @ovuncyazgan 
Updated the archive, batch file is now without custom file path. Please be sure to set your own wallet address.

@davilizh 
After overclocking my 1060 to 4.5GHz there is now a differnce between the master and your build. Your commit is 7% faster for me with single GPU.
Thanks a lot!

**Comment by seedlord** [comment]
GTX 1070 ~1% change
from 30.99 to 31.99 with fluctuations before upto ~35 and now upto ~41.

**Comment by Singman33** [comment]
**WARNING**
Dont compile with `cmake -DBUNDLE=cudaminer -DCOMPUTE=50 ..`
or it will fail at run time. Look like something wrong happen when you specify CUDA version needed

**Comment by ghost** [comment]
The fix has been merged into the new miner "ethminer" on version "ethminer 0.11.0rc1".
See https://github.com/ethereum-mining/ethminer/releases/tag/v0.11.0rc1

**Comment by ghost** [comment]
You have misspelled "--cude-parallel-hash" :-)

**Comment by davilizh** [comment]
@deadgray Terribly sorry, hope this does not affect your use of the code. It seems that someone else have helped me fix it and created a new pull request.

**Comment by davilizh** [comment]
@Genoil Hi, Genoil. Is there any possibility that this code been merged into your master branch? I have added a switch named "--cuda-parallel-hash" to disable and enable my optimization, and the code is merged into Chfast's master branch now. This switch enables people to scale parallel-hash from 1 to 8 to find the best value for their card.

**Comment by ghost** [comment]
@davilizh good joke :-)
Anyway, I tested chfast's version with your great patch included; it seems little slower than older appveyor link compiled version from link above with 1060, almost no difference with 1080, of course I tried new switch.

**Comment by ghost** [comment]
@davilizh It escalates fast: http://cryptomining-blog.com/8852-new-optimized-ethminer-for-nvidia-geforce-gtx-1060-gpus/

**Comment by davilizh** [comment]
@deadgray What's your dram frequency?

**Comment by ghost** [comment]
@davilizh +860 Mhz, so 4665 Mhz.

**Comment by Genoil** [comment]
@davilizh Hi David, I have chosen to cease further development of the fork, so it's unlikely that the patch will be applied. I don't think you have to worry that people won't be able to find the new ethminer fork by Pavel. 

That said, I am looking at your code and find the term PARALLEL_HASH slightly confusing. As far as I'm concerned the hashes were already done in parallel in the first place. The fundamental difference is that rather than doing a single coalesced global read of 128 bytes (8 threads * uint4) for a single hash, you do 4 in series of 32 bytes (2 threads * uint4), for 2 different hashes. I guess it's the reduced memory bus width of GP106 that makes this more efficient. Nevertheless I like it very much.

**Comment by davilizh** [comment]
@deadgray I do not know why. Maybe you have a different dram type. BTW, if you already get the maximum dram bandwidth, my code can not push anymore above the maximum value.

**Comment by ghost** [comment]
@davilizh Even if I can't get more, I'm quite impressed with your patch, good work, my total mining hashrate is now 30MH/s up without investment, which is worth new 1070 card :-)

**Comment by azazhu** [comment]
@Genoil, we just need make sure that 32B is coalesced. The performance is same and we can issue more load instructions to saturate the memory.

**Comment by azazhu** [comment]
@Genoil, we just need make sure that 32B is coalesced. From texture of view, both use full texture bandwidth.  To downstream unit, we can issue more load instructions to saturate the memory.

**Comment by Genoil** [comment]
@azazhu I know and I might have even implemented something similar in the last few years, but either in the wrong way or the hardware I used didn't benefit from this. Nice to see such a dramatic improvement 2 years later.

**Comment by azazhu** [comment]
The arch has been changed a lot :)

**Comment by azazhu** [comment]
@Genoil The arch has been changed a lot :)

**Comment by Genoil** [comment]
@azazhu @davilizh is 'we' you two or is that 'us' in general? Just curious :)

**Comment by whychesslove** [comment]
Hi, @davilizh! Is there any way to apply this to claymore on windows?
I tried it on ethermine with etherminer. There was 24,5Mh/s in console, but only 17Mh/s on the dashboard on ethermine.org. But if i use claymore with same overclocking, i see 23.3Mh/s in console and same on the dashboard.

**Comment by vitoth** [comment]
Tested on windows 10 with 1060 6g, OCed +130 +870
not much difference from claymore, i still need to see 6hr average on nanopool to compare.

Should I try on Linux?
What are the best settings for bat file?
Is nanopool ok?
Are there any instructions/tutorial how to set it up for best performance?

**Comment by davilizh** [comment]
@diversuss sorry, I do not know because I do not know the detail of claymore.

**Comment by justchil** [comment]
I'm seeing an improvement over claymore on my 1070/1060 machine.  

This is a bit OT and I am searching -- anyway to have the reported hashrate to show up with this miner?  Calculated is looking better on nanopool :)

**Comment by chavvdarrr** [comment]
Is there anyway to monitor the miner and take action if stops?
Its not stable, but can't find switch for auto-monitoring.. or with api

**Comment by MichaelA2014** [comment]
Hey guys. I am trying to run it on 4x1070 cards in Windows 10. I get "Application was not able to start correctly (0xc000007b). Click OK to close application"
How do I fix that?
My bat file is as follows:
`setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

ethminer.exe --farm-recheck 200 -U -S eth-us-west1.nanopool.org:9999 -FS eth-us-

east1.nanopool.org:9999 -O mywallet.rigname`

Thank you. 
https://s18.postimg.org/5c7cbh3d5/2017-06-29_7-08-21.jpg

**Comment by chavvdarrr** [comment]
Is your Windows 32 or 64-bit? (64b is a must)
Also I had to download&install vc++ 2015 x64 runtime

**Comment by MichaelA2014** [comment]
my Windows is 10 x64
I installed vcc 2015 x64 redistributable but the error is still there

**Comment by MichaelA2014** [comment]
Do I have to download and install visual studio in addition to vcc 2015 x64?

**Comment by chavvdarrr** [comment]
no 
Also check if your video driver is recent

**Comment by MichaelA2014** [comment]
my driver is the latest 382.53, windows 10 x64. visual c++ redistributable is installed

**Comment by MichaelA2014** [comment]
Got it working. For those who is having the same problem as I did (missing files and 0xc error download and install all in one run times package from `http://www.pcgameshardware.de/Windows-Software-122001/Downloads/All-in-One-Runtimes-Download-1164729/`

**Comment by azazhu** [comment]
@Genoil :)

**Comment by Klintistwood** [comment]
Hello all,

I'm completely new to mining, I don't have a lot of stats to compare with but I started using the previous version of ethminer where I could get a stable 31M/H with my GTX 1070 (with only memory OC and power brought to 80%) and now with this new version I go above 32M/H so there is definitely a very nice improvement !

I had however another question. When running the new version, I got a warning from my antivirus saying that there is a Trojan/Win64.BitCoinMiner inside the executable. It was not the case with the previous version. I downloaded the file from here: https://github.com/ethereum-mining/ethminer/releases/tag/v0.11.0rc1

Any reason to be worried about?

Thanks!

**Comment by ghost** [comment]
@Klintistwood Antivirus software mostly detects miners because 'viruses' / 'ransomware' (or however you want to name it) currently deploy the software on the enemies computers to mine coins for the attacker.

This means it's a false-positive alarm - just ignore it. The miner is safe.

If you worry about it you can try to compile the miner yourself - but this is very technical and should be discussed on e.g. the gitter chat and not on this issue bug tracker.

And yes you are right - the newest version has a very good performance improvement,
thanks to the last patches. 👍 

Btw: The project moved to a new git repository here:  https://github.com/ethereum-mining/ethminer/

**Comment by romanhajas** [comment]
Hello,
I get constantly these errors, I have searched on Google but nothing. Any help is appreciated I use Ubuntu 16.04.2
screenshot from 2017-07-14 02-29-19

**Pull request closed without merging**
