### PR TITLE
Remove some libraries and dependencies

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by Genoil** [comment]
ah this was on my todo list :) thanks a lot!

**Comment by chfast** [comment]
I can continue. Where would you like to stop? To have `ethminer` target only?

**Comment by Genoil** [comment]
Well that would be nice! Ethminer is the only target ive ever built.

**Comment by chfast** [comment]
I will continue working on that in free time. You can merge that in parts if you want.

**Comment by Genoil** [comment]
I'm trying to figure out what parts of /extdep/getstuff.bat I should be able to omit now. For instance Qt doesn't seem neccesary, but it still has some dependencies there.

**Comment by chfast** [comment]
I can tell you that. For sure Qt and LLVM (I've removed EVMJIT).

**Pull request merged**
