### PR TITLE
fix Ubuntu 16.04 build issues

### PR DESCRIPTION
**Pull request by vrodic**

### CODE REVIEW

**Comment by int03h** [comment]
tested on Debian SID .. you should merge these PRs Genoil.

**Comment by jamiis** [comment]
I'm getting a cmake error. I imagine it is something I'm doing wrong. I have confirmed I'm on `vrodic:110`. I'm on ubuntu 16.04 with cuda 7.5. When I run `cmake DBUNDLE=cuda ..` from the build directory I get the following output. I also tried to install `qt5-default`, `libqt5quick5`, and `qtbase5-dev` ... I wasn't sure whether or not the build error was from qt5.

```
-- ctest path: /usr/bin/ctest
 - CryptoPP header: /usr/include
 - CryptoPP lib   : /usr/lib/libcryptopp.so
 - LevelDB header: /usr/include
 - LevelDB lib: /usr/lib/x86_64-linux-gnu/libleveldb.so
 - Jsoncpp header: /usr/include/jsoncpp
 - Jsoncpp lib   : /usr/lib/x86_64-linux-gnu/libjsoncpp.so
 - json-rpc-cpp header: /usr/include
 - json-rpc-cpp lib   : /usr/lib/x86_64-linux-gnu/libjsonrpccpp-common.so;/usr/lib/x86_64-linux-gnu/libjsonrpccpp-server.so;/usr/lib/x86_64-linux-gnu/libjsonrpccpp-client.so
 - microhttpd header: /usr/include
 - microhttpd lib   : /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
 - microhttpd dll   : 
 - readline header: /usr/include
 - readline lib   : /usr/lib/x86_64-linux-gnu/libreadline.so
-- Could NOT find miniupnpc (missing:  MINIUPNPC_INCLUDE_DIR MINIUPNPC_LIBRARY) 
 - gmp header: /usr/include/x86_64-linux-gnu
 - gmp lib   : /usr/lib/x86_64-linux-gnu/libgmp.so
 - curl header: /usr/include
 - curl lib   : /usr/lib/x86_64-linux-gnu/libcurl.so
-- Could NOT find cpuid (missing:  CPUID_INCLUDE_DIR CPUID_LIBRARY) 
 - opencl header: /usr/include
 - opencl lib   : /usr/lib/x86_64-linux-gnu/libOpenCL.so
 - CUDA header: /usr/include
 - CUDA lib   : /usr/lib/x86_64-linux-gnu/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
 - jsonrpcstub location    : ETH_JSON_RPC_STUB-NOTFOUND
CMake Error at cmake/EthDependencies.cmake:144 (find_package):
  By not providing "FindQt5Quick.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Quick",
  but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Quick"
  (requested version 5.4) with any of the following names:

    Qt5QuickConfig.cmake
    qt5quick-config.cmake

  Add the installation prefix of "Qt5Quick" to CMAKE_PREFIX_PATH or set
  "Qt5Quick_DIR" to a directory containing one of the above files.  If
  "Qt5Quick" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:246 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jamis/src/cpp-ethereum-16.04/build/CMakeFiles/CMakeOutput.log".
See also "/home/jamis/src/cpp-ethereum-16.04/build/CMakeFiles/CMakeError.log".
```

**Comment by mailming** [comment]
Please merge it, having lots of issue in building on ubuntu 16

**Comment by Genoil** [comment]
Sorry on holiday. Will merge no earlier than late august.

**Comment by int03h** [comment]
@mailming  grab this one https://github.com/vrodic/cpp-ethereum/tree/110  ..  if you look up the comments he is the author and his fork has them included.  Or you can grab mine, which has the vrodics PR's included, cruft removed,  windows builds removed and all versions dropped  ) https://github.com/int03h/genminer117 , I use it for production testing so it's just easier for me to remember when I need to build a new version quickly..

**Comment by Genoil** [comment]
Sorry to be so late with this. I just blindly merged this because i don't have a linux system handy. I'd also like to update the build instructions if they are any different on Ubuntu 16. Would you mind having a look at them? Thanks!

**Pull request merged**
