### PR TITLE
Reduce CPU usage while waiting for an async task

### PR DESCRIPTION
**Pull request by tpruvot**
Signed-off-by: Tanguy Pruvot <tanguy.pruvot@gmail.com>

### CODE REVIEW

**Comment by Genoil** [comment]
Hey, thanks for you contribution. I'm getting 4% less performance with your PR. Not sure if that is what ppl want :). I'll try to figure out what causes it.

**Comment by tpruvot** [comment]
was only tested on linux, try to reduce the sleep time

2015-08-19 10:31 GMT+02:00 Genoil <notifications@github.com>:

**Comment by Genoil** [comment]
I profiled both versions. Yours gives me 5.8% CPU usage vs. 94.6% of mine. So it is definetely a good thing to have in there. Not sure whta to do at this stage, I fought so hard for these 4% ;-)

**Comment by tpruvot** [comment]
maybe an optional parameter

2015-08-19 11:13 GMT+02:00 Genoil <notifications@github.com>:

**Comment by Genoil** [comment]
yeah i was thinking the same thing..for now it seems a good choice

**Comment by tpruvot** [comment]
Ive no speed reduction at all here using that, did you test on linux or
windows ?

2015-08-19 11:15 GMT+02:00 Genoil <notifications@github.com>:

**Comment by Genoil** [comment]
windows gtx780/Xeon E5. the biggest change can be seen when you increase batch-size to 2^20 (--gpu-batch-size 20). i've added a flag "--high-cpu-load" that basically disables your waiting call.

thanks again. suddenly my NSight report timelines seem to make sense.

**Comment by tpruvot** [comment]
On windows (vstudio), the usleep behavior with low values could be
different,
but this c++ sleep function should take care of that... i guess

Yep me too with nvprof, 50% was on the cudaMemcpyAsync()

2015-08-19 11:45 GMT+02:00 Genoil <notifications@github.com>:

**Pull request merged**
